"use strict";
// Datos locales de la maqueta
const productos=[
{id:1,nombre:"Audífonos Bluetooth AVEC Air",categoria:"Audífonos",descripcion:"Sonido estéreo, estuche de carga y 20 horas de autonomía.",precio:149900,stock:12,icono:"🎧",claves:["audífonos","audifonos","bluetooth","air"]},
{id:2,nombre:"Audífonos Gamer X-Pro",categoria:"Audífonos",descripcion:"Micrófono flexible, sonido envolvente y luces RGB.",precio:189900,stock:7,icono:"🎮",claves:["audífonos","audifonos","gamer","x-pro"]},
{id:3,nombre:"Parlante portátil Beat Mini",categoria:"Audio",descripcion:"Bluetooth 5.3, resistente a salpicaduras y batería de 10 horas.",precio:119900,stock:9,icono:"🔊",claves:["parlante","audio","beat"]},
{id:4,nombre:"Teclado mecánico RGB",categoria:"Periféricos",descripcion:"Interruptores mecánicos, iluminación RGB y distribución en español.",precio:239900,stock:5,icono:"⌨️",claves:["teclado","mecánico","mecanico","rgb"]},
{id:5,nombre:"Mouse inalámbrico Ergo",categoria:"Periféricos",descripcion:"Diseño ergonómico, seis botones y conexión de 2,4 GHz.",precio:89900,stock:10,icono:"🖱️",claves:["mouse","ratón","raton","ergo"]},
{id:6,nombre:"Smartwatch Active",categoria:"Wearables",descripcion:"Monitoreo de actividad, notificaciones y resistencia al agua.",precio:279900,stock:4,icono:"⌚",claves:["smartwatch","reloj","active"]},
{id:7,nombre:"Cargador rápido USB-C",categoria:"Energía",descripcion:"Carga rápida de 30 W con protección contra sobrecarga.",precio:69900,stock:18,icono:"🔌",claves:["cargador","usb-c","energía","energia"]},
{id:8,nombre:"Base refrigerante para portátil",categoria:"Accesorios",descripcion:"Dos ventiladores silenciosos y altura ajustable.",precio:99900,stock:0,icono:"💻",claves:["base","refrigerante","portátil","portatil","accesorio"]}
];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const moneda=v=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(v);
const normalizar=t=>t.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
let carrito=JSON.parse(localStorage.getItem("avecCarrito")||"[]"); let ultimoFoco=null; let chatIniciado=false;

function anunciar(texto){$("#anuncios").textContent="";setTimeout(()=>$("#anuncios").textContent=texto,30)}
function renderProductos(){const q=normalizar($("#busqueda").value);const cat=$("#filtroCategoria").value;const filtrados=productos.filter(p=>(cat==="todos"||p.categoria===cat)&&normalizar(`${p.nombre} ${p.descripcion} ${p.categoria}`).includes(q));$("#resultadoProductos").textContent=`Mostrando ${filtrados.length} resultado${filtrados.length===1?"":"s"}`;$("#listaProductos").innerHTML=filtrados.length?filtrados.map(p=>`<article class="producto" id="producto-${p.id}"><div class="producto-visual" role="img" aria-label="Representación de ${p.nombre}">${p.icono}</div><div class="producto-cuerpo"><span class="categoria">${p.categoria}</span><h3>${p.nombre}</h3><p>${p.descripcion}</p><p class="precio">${moneda(p.precio)}</p><p class="stock ${p.stock===0?"sin-stock":""}">${p.stock>0?`✓ Disponible: ${p.stock} unidades`:`⚠ Agotado: 0 unidades`}</p><div class="cantidad"><label for="cantidad-${p.id}">Cantidad</label><input id="cantidad-${p.id}" type="number" min="1" max="${Math.min(12,p.stock||1)}" value="1" ${p.stock===0?"disabled":""}></div><div class="acciones"><button class="btn primario agregar" data-id="${p.id}" ${p.stock===0?"disabled":""}>Agregar al carrito</button><button class="btn secundario consultar" data-id="${p.id}">Consultar al chatbot</button></div></div></article>`).join(""):`<p class="aviso">No se encontraron productos. Prueba con otra búsqueda o categoría.</p>`}
function guardarCarrito(){localStorage.setItem("avecCarrito",JSON.stringify(carrito));renderCarrito()}
function agregar(id,cantidad=1){const p=productos.find(x=>x.id===id);cantidad=Math.max(1,Math.min(Number(cantidad)||1,p.stock,12));const existente=carrito.find(x=>x.id===id);const actual=existente?existente.cantidad:0;if(actual+cantidad>Math.min(p.stock,12)){anunciar(`No puedes agregar más de ${Math.min(p.stock,12)} unidades de ${p.nombre}.`);return}if(existente)existente.cantidad+=cantidad;else carrito.push({id,cantidad});guardarCarrito();$("#estadoCarrito").textContent=`✓ ${p.nombre} se agregó al carrito.`;anunciar(`${p.nombre} agregado al carrito. Total de unidades: ${carrito.reduce((a,x)=>a+x.cantidad,0)}`)}
function renderCarrito(){const totalUnidades=carrito.reduce((a,x)=>a+x.cantidad,0);$("#contadorCarrito").textContent=totalUnidades;const lista=$("#listaCarrito");if(!carrito.length){lista.innerHTML='<p class="aviso">Tu carrito está vacío. Explora el catálogo para agregar productos.</p>';$("#totalCarrito").textContent=moneda(0);$("#continuarCompra").disabled=true;$("#vaciarCarrito").disabled=true;return}let total=0;lista.innerHTML=carrito.map(item=>{const p=productos.find(x=>x.id===item.id),sub=p.precio*item.cantidad;total+=sub;return `<article class="item-carrito"><strong>${p.nombre}</strong><span>Precio: ${moneda(p.precio)}</span><label>Cantidad <input class="cantidad-carrito" data-id="${p.id}" type="number" min="1" max="${Math.min(12,p.stock)}" value="${item.cantidad}"></label><span>Subtotal: <strong>${moneda(sub)}</strong></span><button class="btn peligro eliminar" data-id="${p.id}">Eliminar</button></article>`}).join("");$("#totalCarrito").textContent=moneda(total);$("#continuarCompra").disabled=false;$("#vaciarCarrito").disabled=false}
function totales(){const subtotal=carrito.reduce((a,i)=>a+productos.find(p=>p.id===i.id).precio*i.cantidad,0);const envio=subtotal?15000:0;return{subtotal,envio,total:subtotal+envio}}
function resumenCompra(){const t=totales();$("#resumenCompra").innerHTML=carrito.map(i=>{const p=productos.find(x=>x.id===i.id);return `<div class="resumen-linea"><span>${p.nombre} × ${i.cantidad}</span><strong>${moneda(p.precio*i.cantidad)}</strong></div>`}).join("")+`<div class="resumen-linea"><span>Subtotal</span><strong>${moneda(t.subtotal)}</strong></div><div class="resumen-linea"><span>Envío</span><strong>${moneda(t.envio)}</strong></div><div class="resumen-linea"><span>Total</span><strong>${moneda(t.total)}</strong></div>`}
function abrirModal(id,disparador=document.activeElement){ultimoFoco=disparador;const m=$(id);m.classList.remove("oculto");document.body.classList.add("modal-abierto");setTimeout(()=>{const foco=m.querySelector("button:not([disabled]),input:not([disabled])");(foco||m).focus()},20)}
function cerrarModal(modal){modal.classList.add("oculto");if(!$$('.modal:not(.oculto)').length)document.body.classList.remove("modal-abierto");if(ultimoFoco)ultimoFoco.focus()}
function atraparFoco(e,modal){if(e.key!=="Tab")return;const focos=$$('button:not([disabled]),a[href],input:not([disabled]),select,textarea').filter(x=>modal.contains(x));if(!focos.length)return;const primero=focos[0],ultimo=focos[focos.length-1];if(e.shiftKey&&document.activeElement===primero){e.preventDefault();ultimo.focus()}else if(!e.shiftKey&&document.activeElement===ultimo){e.preventDefault();primero.focus()}}
function abrirChat(mensaje=""){const chat=$("#chatbot");chat.classList.remove("oculto");chat.setAttribute("aria-expanded","true");$("#chatCuerpo").classList.remove("oculto");if(!chatIniciado){mensajeBot("¡Hola! Soy AVEC Bot. Puedo ayudarte a consultar productos, precios, disponibilidad y el estado de tus pedidos. ¿Qué deseas buscar?");chatIniciado=true}if(mensaje){$("#entradaChat").value=mensaje;enviarChat(mensaje)}else $("#entradaChat").focus()}
function mensajeBot(texto,producto=null){const d=document.createElement("div");d.className="mensaje bot";d.innerHTML=`<strong>AVEC Bot</strong><br>${texto}`;if(producto)d.innerHTML+=`<div class="mini-acciones"><button data-chat-agregar="${producto.id}">Agregar al carrito</button><button data-ver="${producto.id}">Ver producto</button><button data-asesor="1">Hablar con un asesor</button></div>`;$("#mensajesChat").appendChild(d);$("#mensajesChat").scrollTop=$("#mensajesChat").scrollHeight}
function enviarChat(texto){texto=texto.trim();if(!texto)return;const u=document.createElement("div");u.className="mensaje usuario";u.innerHTML=`<strong>Tú</strong><br>${texto.replace(/[<>&]/g,m=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[m]))}`;$("#mensajesChat").appendChild(u);mensajeBot("Consultando inventario…");$("#entradaChat").value="";const espera=700+Math.floor(Math.random()*501);setTimeout(()=>{const mensajes=$$("#mensajesChat .mensaje.bot");const cargando=mensajes[mensajes.length-1];if(cargando&&cargando.textContent.includes("Consultando inventario"))cargando.remove();responder(texto)},espera)}
function responder(texto){const n=normalizar(texto);if(n.includes("pedido")){mensajeBot("El pedido simulado #AVEC-2026-1048 está en preparación. La entrega estimada es el 5 de octubre de 2026.");return}if(n.includes("asesor")||n.includes("ayuda")){mensajeBot("He registrado tu solicitud. En esta maqueta, un asesor humano simulado continuaría la atención. Tu carrito permanece guardado.");return}if(n.includes("ver productos")||n.includes("producto")){mensajeBot("Tenemos audífonos, parlantes, teclados, mouse, smartwatches, cargadores y accesorios. Puedes abrir el catálogo para comparar precios y existencias.");return}let p=productos.find(x=>x.claves.some(c=>n.includes(normalizar(c))));if(!p&&["precio","disponibilidad","inventario"].some(k=>n.includes(k)))p=productos[0];if(p){mensajeBot(p.stock?`Sí. ${p.nombre} tiene ${p.stock} unidades disponibles. Su precio es de ${moneda(p.precio)}.`:`${p.nombre} está agotado actualmente. Puedes hablar con un asesor para conocer alternativas.`,p);return}mensajeBot("No encontré una coincidencia exacta. Puedes consultar audífonos, parlantes, teclados, mouse, relojes inteligentes o solicitar la ayuda de un asesor.")}
function validarEnvio(){const reglas={nombre:[v=>v.trim().split(/\s+/).length>=2,"Escribe tu nombre y al menos un apellido."],correo:[v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),"Escribe un correo válido, por ejemplo: nombre@correo.com."],telefono:[v=>/^\d{10}$/.test(v),"El teléfono debe contener 10 números, por ejemplo: 3001234567."],ciudad:[v=>v.trim().length>=2,"Escribe el nombre de la ciudad."],direccion:[v=>v.trim().length>=6,"Escribe una dirección completa de al menos 6 caracteres."]};let primero=null;Object.entries(reglas).forEach(([id,[prueba,mensaje]])=>{const campo=$(`#${id}`),error=$(`#error${id[0].toUpperCase()+id.slice(1)}`),valido=prueba(campo.value);campo.setAttribute("aria-invalid",String(!valido));error.textContent=valido?"":`⚠ ${mensaje}`;if(!valido&&!primero)primero=campo});if(primero){primero.focus();anunciar("Hay errores en el formulario. Revisa el primer campo marcado.");return false}return true}
function mostrarResultado(tipo){const aprobado=tipo==="aprobado";$("#contenidoResultado").innerHTML=aprobado?`<div><div class="resultado-icono" aria-hidden="true">✅</div><h2 id="resultadoTitulo">Pago aprobado</h2><p>La compra simulada fue confirmada. No se realizó un cobro real.</p><button class="btn primario finalizar" type="button">Ver mi pedido</button></div>`:`<div class="resultado-error"><div class="resultado-icono" aria-hidden="true">⚠️</div><h2 id="resultadoTitulo">Pago rechazado</h2><p>No pudimos procesar el pago. No se realizó ningún cobro y tu carrito continúa guardado. Verifica el método de pago o intenta nuevamente.</p><div class="acciones"><button class="btn primario reintentar" type="button">Reintentar pago</button><button class="btn secundario cambiar" type="button">Cambiar método</button><button class="btn secundario abrir-chat resultado-asesor" type="button">Hablar con un asesor</button></div></div>`;abrirModal("#modalResultado")}

// Inicialización y eventos
[...new Set(productos.map(p=>p.categoria))].sort().forEach(c=>$("#filtroCategoria").insertAdjacentHTML("beforeend",`<option>${c}</option>`));renderProductos();renderCarrito();$("#anio").textContent=new Date().getFullYear();
$("#menuBtn").addEventListener("click",()=>{const abierto=$("#menuPrincipal").classList.toggle("abierto");$("#menuBtn").setAttribute("aria-expanded",String(abierto))});$$("#menuPrincipal a").forEach(a=>a.addEventListener("click",()=>{$("#menuPrincipal").classList.remove("abierto");$("#menuBtn").setAttribute("aria-expanded","false")}));
$("#busqueda").addEventListener("input",renderProductos);$("#filtroCategoria").addEventListener("change",renderProductos);$("#limpiarFiltros").addEventListener("click",()=>{$("#busqueda").value="";$("#filtroCategoria").value="todos";renderProductos();$("#busqueda").focus()});
document.addEventListener("click",e=>{const agregarBtn=e.target.closest(".agregar");if(agregarBtn){const id=+agregarBtn.dataset.id;agregar(id,$(`#cantidad-${id}`).value)}const consultar=e.target.closest(".consultar");if(consultar){const p=productos.find(x=>x.id===+consultar.dataset.id);abrirChat(p.nombre)}if(e.target.closest(".abrir-chat")){abrirChat(e.target.closest(".abrir-chat").dataset.mensaje||"")}const eliminar=e.target.closest(".eliminar");if(eliminar&&confirm("¿Deseas eliminar este producto del carrito?")){carrito=carrito.filter(x=>x.id!==+eliminar.dataset.id);guardarCarrito();anunciar("Producto eliminado del carrito.")}if(e.target.dataset.chatAgregar)agregar(+e.target.dataset.chatAgregar,1);if(e.target.dataset.ver){location.hash=`#producto-${e.target.dataset.ver}`;$("#chatbot").classList.add("oculto")}if(e.target.dataset.asesor)mensajeBot("Un asesor humano simulado atendería tu solicitud. No se enviaron datos a servicios externos.");if(e.target.closest(".cerrar-modal"))cerrarModal(e.target.closest(".modal"));if(e.target.classList.contains("finalizar")){carrito=[];guardarCarrito();cerrarModal($("#modalResultado"));location.hash="#pedidos"}if(e.target.classList.contains("reintentar")||e.target.classList.contains("cambiar")){cerrarModal($("#modalResultado"));abrirModal("#modalEnvio")}if(e.target.classList.contains("resultado-asesor")){cerrarModal($("#modalResultado"));abrirChat("asesor")}});
$("#listaCarrito").addEventListener("change",e=>{if(!e.target.classList.contains("cantidad-carrito"))return;const item=carrito.find(x=>x.id===+e.target.dataset.id),p=productos.find(x=>x.id===item.id);let v=Math.max(1,Math.min(+e.target.value||1,p.stock,12));item.cantidad=v;e.target.value=v;guardarCarrito();anunciar(`Cantidad actualizada a ${v}.`)});
$("#vaciarCarrito").addEventListener("click",()=>{if(carrito.length&&confirm("¿Deseas vaciar todo el carrito?")){carrito=[];guardarCarrito();anunciar("El carrito quedó vacío.")}});$("#continuarCompra").addEventListener("click",e=>{if(!carrito.length)return;resumenCompra();abrirModal("#modalCompra",e.currentTarget)});$("#volverModal").addEventListener("click",()=>cerrarModal($("#modalCompra")));$("#cancelarCompra").addEventListener("click",()=>{if(confirm("¿Deseas cancelar la compra y eliminar los productos del carrito?")){carrito=[];guardarCarrito();cerrarModal($("#modalCompra"));anunciar("Compra cancelada. El carrito fue vaciado.")}});$("#confirmarCompra").addEventListener("click",()=>{cerrarModal($("#modalCompra"));abrirModal("#modalEnvio")});$("#volverConfirmacion").addEventListener("click",()=>{cerrarModal($("#modalEnvio"));resumenCompra();abrirModal("#modalCompra")});
$("#formEnvio").addEventListener("submit",e=>{e.preventDefault();if(!validarEnvio())return;const tipo=new FormData(e.currentTarget).get("resultadoPago");cerrarModal($("#modalEnvio"));mostrarResultado(tipo)});
$$(".abrir-chat").forEach(b=>b.addEventListener("click",()=>{}));$("#cerrarChat").addEventListener("click",()=>{$("#chatbot").classList.add("oculto");$("#chatbot").setAttribute("aria-expanded","false")});$("#minimizarChat").addEventListener("click",()=>{const oculto=$("#chatCuerpo").classList.toggle("oculto");$("#chatbot").setAttribute("aria-expanded",String(!oculto));$("#minimizarChat").textContent=oculto?"+":"−"});$("#formChat").addEventListener("submit",e=>{e.preventDefault();enviarChat($("#entradaChat").value)});$$('[data-consulta]').forEach(b=>b.addEventListener("click",()=>enviarChat(b.dataset.consulta)));
document.addEventListener("keydown",e=>{const modal=$$(".modal:not(.oculto)").at(-1);if(modal){if(e.key==="Escape")cerrarModal(modal);else atraparFoco(e,modal);return}if(e.key==="Escape"&&!$("#chatbot").classList.contains("oculto")){$("#chatbot").classList.add("oculto");$("#chatbot").setAttribute("aria-expanded","false")}});